/*
 * Ieee80211HaLowMgmtFrames_m.h
 *
 *  Created on: 10-Jan-2017
 *      Author: KAUSHIK NAGARAJAN
 */

#ifndef IEEE80211HALOWMGMTFRAMES_M_H_
#define IEEE80211HALOWMGMTFRAMES_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// cplusplus {{
#include "inet/linklayer/common/MACAddress.h"
#include "inet/linklayer/ieee80211/mac/Ieee80211Frame_m.h"
// }}


namespace inet {
namespace ieee80211 {

// cplusplus {{
#define PREQElemLen 11
#define PERRElemLen 13
// }}

/**
 * Struct generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrames.msg:45 by nedtool.
 */

class Ieee80211HaLowAssociationResponseFrameBody : public ::inet::ieee80211::Ieee80211FrameBody
{
  protected:
    int statusCode_var;
    short aid_var;
    Ieee80211SupportedRatesElement supportedRates_var;
    uint64_t AssociationID_var;

  private:
    void copy(const Ieee80211HaLowAssociationResponseFrameBody& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Ieee80211HaLowAssociationResponseFrameBody&);

  public:
    Ieee80211HaLowAssociationResponseFrameBody();
    Ieee80211HaLowAssociationResponseFrameBody(const Ieee80211HaLowAssociationResponseFrameBody& other);
    virtual ~Ieee80211HaLowAssociationResponseFrameBody();
    Ieee80211HaLowAssociationResponseFrameBody& operator=(const Ieee80211HaLowAssociationResponseFrameBody& other);
    virtual Ieee80211HaLowAssociationResponseFrameBody *dup() const {return new Ieee80211HaLowAssociationResponseFrameBody(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getStatusCode() const;
    virtual void setStatusCode(int statusCode);
    virtual short getAid() const;
    virtual void setAid(short aid);
    virtual Ieee80211SupportedRatesElement& getSupportedRates();
    virtual const Ieee80211SupportedRatesElement& getSupportedRates() const {return const_cast<Ieee80211HaLowAssociationResponseFrameBody*>(this)->getSupportedRates();}
    virtual void setSupportedRates(const Ieee80211SupportedRatesElement& supportedRates);
     virtual uint64_t getassociationID() const;
      virtual void setassociationID(uint64_t AssociationIdentifier);
};

inline void doPacking(cCommBuffer *b, Ieee80211HaLowAssociationResponseFrameBody& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Ieee80211HaLowAssociationResponseFrameBody& obj) {obj.parsimUnpack(b);

}


class Ieee80211HaLowAssociationResponseFrame : public inet::ieee80211::Ieee80211ManagementFrame
{
  protected:
    Ieee80211HaLowAssociationResponseFrameBody body_var;

  private:
    void copy(const Ieee80211HaLowAssociationResponseFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Ieee80211HaLowAssociationResponseFrame&);

  public:
    Ieee80211HaLowAssociationResponseFrame(const char *name=NULL, int kind=0);
    Ieee80211HaLowAssociationResponseFrame(const Ieee80211HaLowAssociationResponseFrame& other);
    virtual ~Ieee80211HaLowAssociationResponseFrame();
    Ieee80211HaLowAssociationResponseFrame& operator=(const Ieee80211HaLowAssociationResponseFrame& other);
    virtual Ieee80211HaLowAssociationResponseFrame *dup() const {return new Ieee80211HaLowAssociationResponseFrame(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual Ieee80211HaLowAssociationResponseFrameBody& getBody();
    virtual const Ieee80211HaLowAssociationResponseFrameBody& getBody() const {return const_cast<Ieee80211HaLowAssociationResponseFrame*>(this)->getBody();}
    virtual void setBody(const Ieee80211HaLowAssociationResponseFrameBody& body);
};

inline void doPacking(cCommBuffer *b, Ieee80211HaLowAssociationResponseFrame& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Ieee80211HaLowAssociationResponseFrame& obj) {obj.parsimUnpack(b);}


}//ieee80211
}//inet



#endif /* IEEE80211HALOWMGMTFRAMES_M_H_ */
